n = int(input("Uma distância em metros: "))
print("{}m equivale à:".format(n))
print("{}km".format(n*0.001))
print("{}hm".format(n*0.01))
print("{:.1f}dam".format(n*0.1))
print("{}dm".format(n*10))
print("{}cm".format(n*100))
print("{}mm".format(n*1000))